Add API to return manticore status information
smartdevicelink/manticore pull request #174
Opened 2022-08-30 15:06 UTC by RaedAlmomani

Add API to return manticore status information.

2022-09-12 20:29 UTC, crokita requested changes
see feedback

2022-09-13 12:33 UTC, RaedAlmomani commented on api/v2/index.js
> +        const wsAddress = await websocket.getPasscode();
Done!!

2022-09-13 13:28 UTC, RaedAlmomani commented on api/v2/index.js
> +        const wsAddress = await websocket.getPasscode();
Done!!

2022-09-13 13:34 UTC, RaedAlmomani commented on api/v2/index.js
> +    router.get(`${API_PREFIX}/info`, async (ctx, next) => {
Done!!

2022-09-13 13:41 UTC, RaedAlmomani commented on api/v2/index.js
Done!

2022-10-27 15:10 UTC, crokita requested changes
See feedback

2022-10-27 16:11 UTC, RaedAlmomani commented on api/v2/app/interfaces/websocket/simple/index.js
> +async function isIdExist (id) {
Done!

2022-10-28 14:59 UTC, crokita requested changes

2022-10-28 14:59 UTC, crokita commented on api/v2/index.js
> +            ctx.response = updateCtxRespone(ctx.response);
```suggestion
        if (config.modes.haproxy) {
            ctx.response = updateCtxRespone(ctx.response);
        }
```

2022-10-28 15:41 UTC, crokita approved these changes

2022-10-28 15:44 UTC, merged